### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by XionghuiYe** [sysu19351158/FPB-FOMM#1]
作者你好，你发布的代码中的FramesDataset的out['driving']和out['source']都是numpy数组的形式，可是模型对输入的要求是张量类型，这地方是不是出错了，请解释下，谢谢

**Comment by XionghuiYe** [comment]
还有就是在该dataset中我没看到关于将视频数据转为灰度图的相关操作，是不是漏发了其它dataset的py文件？

**Comment by zylye123** [comment]
Hi. Sorry for the late reply. 

The ``dataloader`` construction part is dependent on the implementation of first order motion model ([FOMM](https://github.com/AliaksandrSiarohin/first-order-model)). You may refer to that repo.

As for the grayscale image issue. This repository is targeted at the micro-expression generation task. The SAMM dataset, which is a commonly used micro-expression dataset itself is grayscale. So we use grayscale images for demonstration here.

**Comment by XionghuiYe** [comment]
> Hi. Sorry for the late reply.
> 
> The `dataloader` construction part is dependent on the implementation of first order motion model ([FOMM](https://github.com/AliaksandrSiarohin/first-order-model)). You may refer to that repo.
> 
> As for the grayscale image issue. This repository is targeted at the micro-expression generation task. The SAMM dataset, which is a commonly used micro-expression dataset itself is grayscale. So we use grayscale images for demonstration here.

Thank you for taking the time to reply amidst your busy schedule. I think the second issue has been resolved, but as for the first issue, after reading the FOMM documentation, I feel that it does not mention any operations related to converting numpy data into tensor types suitable for neural network training. Could you please explain why this is the case?

**Comment by XionghuiYe** [comment]
> Hi. Sorry for the late reply.
> 
> The `dataloader` construction part is dependent on the implementation of first order motion model ([FOMM](https://github.com/AliaksandrSiarohin/first-order-model)). You may refer to that repo.
> 
> As for the grayscale image issue. This repository is targeted at the micro-expression generation task. The SAMM dataset, which is a commonly used micro-expression dataset itself is grayscale. So we use grayscale images for demonstration here.

If there are operations to convert numpy to tensor, please find them and show them to me. I would greatly appreciate it.

**Comment by zylye123** [comment]
Hi.

Apparently, the transform operation is automatically done within the [PyTorch](https://github.com/pytorch/pytorch/blob/main/torch/utils/data/_utils/collate.py#L63).

For Chinese readers, you may also refer to this [blog](https://zhuanlan.zhihu.com/p/512774389).

**Comment by XionghuiYe** [comment]
> Hi.
> 
> Apparently, the transform operation is automatically done within the [PyTorch](https://github.com/pytorch/pytorch/blob/main/torch/utils/data/_utils/collate.py#L63).
> 
> For Chinese readers, you may also refer to this [blog](https://zhuanlan.zhihu.com/p/512774389).

Thank you very much for your patient response! It helps me to make up for my lack of knowledge in PyTorch. Dalao，Niubee(QWQ)！
